### ISSUE TITLE
Hello, I want to know exactly what the structure of the model is.

### ISSUE THREAD

**Issue by xiaoxuesheng180** [tyshiwo1/DiM-DiffusionMamba#11]
Hello, I want to know exactly what the structure of the model is, but which file(.py) is the structure design of the model? Could you let me know? Thank you very much.
您好，我想知道模型的结构具体是什么样的，但是我不太清楚模型的结构设计是在哪一个.py文件里（或者由哪几个文件构成）？可以告知我一下吗？非常感谢。

**Comment by awesomeNabi** [comment]
i aslo want to know,have you resolved it?

**Comment by 97KangSH** [comment]
As I reviewed the code, it seems that the model's structure is defined in the `Mamba2DModel` class, 
located in `mamba_attn_diff/models/mamba_2d.py`.
