### ISSUE TITLE
Questions about training time

### ISSUE THREAD

**Issue by ZhiyuanLi218** [tyshiwo1/DiM-DiffusionMamba#4]
Hi, excuse me. How much time did it take to train a Large model of Imagenet 256\*256 with 8\*A100 80G?

**Comment by tyshiwo1** [comment]
About 9 days.

Mamba is slower than Transformer when the input sequence is short. We have analyzed the speed in Figure 3 of our paper.

Other papers like [1] also find such a phenomenon.

[1] Yang S, Wang B, Shen Y, et al. Gated linear attention transformers with hardware-efficient training[J]. arXiv preprint arXiv:2312.06635, 2023.
